---
name: lint
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build-requirements.txt
          pip install -r requirements.txt
      - name: Lint
        run: |
          mypy --install-types --non-interactive --ignore-missing-imports .
          pylint monet.py
          black .
